library(tidyverse)
library(rprime)
library(wrapr)


# split data into three time frames

#' An Eprime conversion function
#' 
#' A function to convert eprime text files to r dataframes
#' This function converts eprime data into R usable dataframes. It will take in .eprime files, and will return a dataframe.
#' @param wm_path specifies the file path to the eprime file of interest
#' @export
#' @return dataframe containing all eprime entries for Accuracy, Reaction time (RT), and Warning type
#' @keywords eprime, dataframe

eprime_to_dataframe <- function(wm_path) {
  # Read in a text file generated by Eprime
  wm_lines <- read_eprime(wm_path)
  # Convert lines from an Eprime file into EprimeFrame objects
  wm_frames <- FrameList(wm_lines)
  # Make it a data frame.
  experiment_df <- to_data_frame(wm_frames)
  
  
  # Select the columns we want for a tibble called "dat".
  experiment_df <- experiment_df %>%
    dplyr::select(FlankerType,SlideTarget.ACC, SlideTarget.RT, WarningType) %>%
    
    # Convert data types 
    mutate(SlideTarget.ACC = as.numeric(SlideTarget.ACC), 
           SlideTarget.RT = as.numeric(SlideTarget.RT),
           
           # characterize cue type 
           cue = ifelse(WarningType == "up" | WarningType == "down", "orienting", WarningType),
           )
  # find the length of a third of the experiment
  third_length <- floor(nrow(experiment_df)/3)
  # add new column classifying which third the observation was in
  experiment_df$third <- if((3* third_length) == nrow(experiment_df)) {
    rep(1:3, third_length)
  } else {
      c(rep(1, third_length), rep(2, third_length), rep(3, nrow(experiment_df) - (2* third_length)))
    } 
  # return the experiment df
  experiment_df
}


#' Median response time calcualtor
#'
#' A function that calculates median values of repsonse times from ANT data with the option to split data into thirds or take the median over all observations.
#' @param df the dataframe containing ANT data for calculating median reaction times
#' @param thirds specifies whether the medians should be calculated for eacah third of the observation time separately. Default is FALSE.
#' @return Returns median(s) reaction times for the specified subject as a dataframe 
#' @export

calc_systems <- function(df, thirds = FALSE) {
  gr <- NULL
  gr <- if(thirds == TRUE) {quote(third)} else {third <-0 }
  
  # compute median overall RT and accuracy
  ACC <- df %>%
    group_by(!!gr) %>%
    summarize("acc" = mean(SlideTarget.ACC, na.rm = TRUE))
  RT <- df %>%
    group_by(!!gr) %>%
    summarize("rt" = median(df$SlideTarget.RT, na.rm=TRUE))
  
  # find medians of cues 
  medians <- df %>%
    # Filter only accurate attempts
    filter(SlideTarget.ACC == 1) %>%
    group_by(cue, !!gr)%>%
    
    # find the medians
    summarize(med = median(SlideTarget.RT, na.rm = TRUE)) %>%
    pivot_wider(names_from = cue, values_from=med)
  
    # All calculations are done on medians for stability since these distributions are often quite skewed.
  
  # Calculate alerting
  # Cues: No - double  
  alerting <- medians["no"] - medians["double"]
  
  # Calculate Orienting  
  # Cues: Center - Orienting
  orienting <- medians["center"] - medians["orienting"]
  
  # Calculate conflict
  # Flankertype: Incongruent - congruent
  conflict <- df %>%
    # Filter for the correct cues and only accurate attempts
    filter(FlankerType == "incongruent" | FlankerType == "congruent" & SlideTarget.ACC == 1) %>%
    group_by(FlankerType, !!gr) %>%
    
    # find the medians
    summarize(med = median(SlideTarget.RT, na.rm = TRUE)) %>%
    
    pivot_wider(names_from = FlankerType, values_from = med) %>%
    
    # take the difference of the medians
    mutate(conflict = incongruent - congruent)
    
  results <- tibble("Alert" = alerting$no, "Orient" = orienting$center, "Conflict" = conflict$conflict,
                    "ACC" = ACC$acc, "Median_RT" = RT$rt)
  results$Third <- if(thirds == TRUE) {1:nrow(results)} else {0}
  # attach subject grid
  # note that it references the "i" from the higher up for loop
  subject <- str_extract(files[[i]], "-[:alnum:]*")
  subject <- sub(".", "", subject)

  # attach year of observation
  year <- str_extract(files[[i]], "[1-3]")
  
  
  
  cbind(subject, year, results)
}

#' Attention systems calculator 
#'
#' A function that loads eprime data and calculates median response times from ANT data with the option to split data into thirds or take the median over all observations.
#' @param file specifies the file path to the eprime file of interest 
#' @param thirds specifies whether the medians should be calculated for eacah third of the observation time separately. Default is FALSE.
#' @return Returns median(s) reaction times for the specified subject as a dataframe 
#' @export
#' @example 
#' # NOTE: you need to have tidyverse, rprime, rstudioapi, and wrapr installed.
#' # Install these in R with the following command <install.packages(c("tidyverse", "rprime", "wrapr", "rstudioapi")) >
#'
#' library(rstudioapi)
#' ######################
#' # User input
#'
#' # Enter the file path for the ANT .txt data
#' ANT_folder <- selectDirectory()
#'
#' # End User input
#' ######################
#' # Source the script with ANT functions
#' source("Scripts/ANT-functions.R")
#'
#'
#' # Extract the files in that folder 
#' files <- list.files(ANT_folder, full.names = TRUE)
#'
#' # select only the .txt files
#' files <- files[str_ends(files, ".txt")]
#'
#' # Seed empty df to save attention network results
#' results <- data.frame()
#'
#'
#' # compute attention network metrics for each experiment
#' for (i in 1:20) {
#'   print(paste("Processing experiment", i))
#'   results <- rbind(results, Attention_systems_calculator(files[i], thirds = FALSE))
#'   results <- rbind(results, Attention_systems_calculator(files[i], thirds = TRUE))
#' }
#'
#' r1 <- results
#' r2 <- results
#' r3 <- results
#' #### This is for storing and combining results from multiple years.
#' # 
#' results <- rbind(r1, r2, r3)
#'
#' # save results as a csv if you want.
#' write.csv(results, "ANT_results.csv")


Attention_systems_calculator <- function(file, thirds = FALSE) {
  # convert eprime text to dataframe
  dat <- eprime_to_dataframe(test_filepath)
  
  # Calculate and return results
  calc_systems(dat, thirds)
  
}

